export const ERROR_MESSAGE: Record<string, string> = {
  SUCCESS: 'Nhận dữ liệu thành công',

  USER_NOT_FOUND: 'Email không tồn tại',
  WRONG_PASSWORD: 'Sai mật khẩu',
  UNAUTHORIZED: 'Không có quyền truy cập',
  TOKEN_EXPIRED: 'Token hết hạn',
  VALIDATION_ERROR: 'Dữ liệu không hợp lệ',
  INTERNAL_ERROR: 'Lỗi hệ thống',
  USER_ALREADY_EXISTS: 'Email đã tồn tại',
  PRODUCT_NOT_FOUND: 'Sản phẩm không tồn tại',
  PRODUCT_ALREADY_EXISTS: 'SKU đã tồn tại',
  STAFF_NOT_FOUND: 'Nhân viên không tồn tại',
  STAFF_ALREADY_EXISTS: 'Email hoặc số điện thoại nhân viên đã tồn tại',
  CUSTOMER_NOT_FOUND: 'Khách hàng không tồn tại',
  CUSTOMER_ALREADY_EXISTS: 'Số điện thoại khách hàng đã tồn tại',
  INSUFFICIENT_STOCK: 'Số lượng tồn kho không đủ',
  INVALID_STOCK_ADJUSTMENT: 'Điều chỉnh tồn kho không hợp lệ',
  SALES_ORDER_NOT_FOUND: 'Đơn hàng không tồn tại',
  INVALID_DISCOUNT: 'Giảm giá không hợp lệ',
  INVALID_PAID_AMOUNT: 'Số tiền thanh toán không hợp lệ',
  INVALID_RECEIPT_AMOUNT: 'Số tiền thu không hợp lệ',
  RECEIPT_EXCEEDS_DEBT: 'Số tiền thu vượt quá công nợ hiện tại',
  INVALID_DATE_RANGE: 'Khoảng thời gian lọc không hợp lệ',
};
